OPENAPI_VERSION = '3.0.2'
OPENAPI_REDOC_PATH = 'redoc'
OPENAPI_REDOC_VERSION = 'next'
OPENAPI_SWAGGER_UI_PATH = 'swagger'
OPENAPI_SWAGGER_UI_VERSION = '3.23.5'
OPENAPI_URL_PREFIX = 'doc'
MODULE_BASE_PREFIX = '/api/v1'

SQLALCHEMY_DATABASE_URI = 'postgresql://smorest-admin:smorest2019@localhost:5432/my-smorest'
SQLALCHEMY_TRACK_MODIFICATIONS = false

SECRET_KEY = '6.ix6D={-+]qK;>Hd9xTQ\iU&!`O&W'
JWT_SECRET_KEY = 'UiXC{?%6vBoqz?F#5w$^J{PNQxhLyW'
JWT_BLACKLIST_ENABLED = true
JWT_BLACKLIST_TOKEN_CHECKS = ['access', 'refresh']
JWT_TOKEN_LOCATION = ['headers', 'query_string']
JWT_QUERY_STRING_NAME = 'token'

SECURITY_LOGIN_URL = '/admin/login'
SECURITY_LOGOUT_URL = '/admin/logout'
SECURITY_POST_LOGIN_VIEW = '/admin/'
SECURITY_POST_LOGOUT_VIEW = '/admin/'
SECURITY_REGISTER_URL = '/admin/register'
SECURITY_REGISTERABLE = true
SECURITY_PASSWORD_SALT = 'KCzR\0%1\@)xFSo)\N1px9<W*H?Gs#'
BABEL_DEFAULT_LOCALE = 'zh_cn'
BABEL_DEFAULT_TIMEZONE = 'Asia/Shanghai'

MAIL_SERVER = 'smtp.exmail.qq.com'
MAIL_PORT = 465
MAIL_USE_SSL = true
MAIL_USERNAME = ''
MAIL_DEFAULT_SENDER = ''
MAIL_PASSWORD = ''

CELERY_MONGODB_SCHEDULER_COLLECTION = 'schedules'
CELERY_RESULT_BACKEND = 'app.extensions.celerybackend:MongoBackend'
CELERY_BROKER_URL = "amqp://"
CELERY_IMPORTS = ["app.backtasks"]
CELERY_TASK_SERIALIZER = "bson"
CELERY_ACCEPT_CONTENT = ["bson", "json"]
CELERY_EVENT_SERIALIZER = "bson"
CELERY_RESULT_SERIALIZER = "bson"

PREFERRED_URL_SCHEME = 'http'

[MONGODB_SETTINGS]
    db = 'my-smorest'
    username = 'smorest-admin'
    password = 'smorest2019'
    host = '127.0.0.1'
    authentication_source = 'my-smorest'
    port = 27017
    connect = false
